version: '3'

services:
  nextjs:
    ports:
      - 3000:3000
    build:
      context: .
      target: development
    command: npm run dev
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next